version: '3.8'

services:
  ondemand:
    container_name: ondemand
    hostname: ondemand
    build:
      context: ./ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - ondemand-network
      - slurm-network
    depends_on:
      - ldap

  ldap: 
    build:
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - ondemand-network

  slurm-controller:
    build:
      context: ./slurm-controller
    networks:
      - slurm-network

networks:
  ondemand-network:
  slurm-network:

volumes:
  ldap_data:
  ldap_config:
